use_frameworks!

platform :ios, '9.0'

target 'TKUISDK_Example' do
  pod 'TKUISDK', :path => '../'

  target 'TKUISDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
