# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://gitee.com/mirrors/CocoaPods-Specs.git'

target 'TKUISDK' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'QCloudCOSXML'
  pod 'SSZipArchive', '2.1.5'
  pod 'Masonry', '1.1.0'
  pod 'Bugly', '2.5.0'
  pod 'MJRefresh'
  
end
